### ISSUE TITLE
error with FlowRouter SSR

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#118]
```
W20160322-23:17:13.659(7)? (STDERR)
W20160322-23:17:13.660(7)? (STDERR) C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:245
W20160322-23:17:13.660(7)? (STDERR)                                             throw(ex);
W20160322-23:17:13.660(7)? (STDERR)                                                   ^
W20160322-23:17:13.660(7)? (STDERR) TypeError: Object [object Object] has no method 'wait'
W20160322-23:17:13.660(7)? (STDERR)     at src/meteor.startup.js:5:1
W20160322-23:17:13.660(7)? (STDERR)     at src/meteor.startup.js:6:1
W20160322-23:17:13.660(7)? (STDERR)     at D:\DEV\Meteor\WEBPACK\kickstart\.meteor\local\build\programs\server\boot.js:242:10
W20160322-23:17:13.660(7)? (STDERR)     at Array.forEach (native)
W20160322-23:17:13.661(7)? (STDERR)     at Function._.each._.forEach (C:\Users\lyquo\AppData\Local\.meteor\packages\meteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160322-23:17:13.661(7)? (STDERR)     at D:\DEV\Meteor\WEBPACK\kickstart\.meteor\local\build\programs\server\boot.js:137:5
```
no method 'wait'...
i try to remove FlowRouter.wait() on meteor.startup.js too, but not happen.

**Comment by lyquocnam** [comment]
omg i put meteor.startup.js outside client folder.
my mistake...
