### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/meteor-webpack#145]
Hi, the issues with deployment seem that they are not fixed ;( While the production now runs and does not complain for the CSS, when deploying to Galaxy following appears:

```
Errors prevented deploying:
While processing files with webpack:webpack (for target os.linux.x86_64):
fs.js:666:18: ENOENT, no such file or directory '/Users/tomi/Documents/Programming/Github/Mantra-Clara/node_modules/esprima-fb/'
at Object.fs.readdirSync (fs.js:666:18)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:655:21)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:653:83)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:653:83)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:653:83)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at compile (packages/webpack:webpack/plugin/WebpackCompiler.js:589:9)
at runWebpack (packages/webpack:webpack/plugin/WebpackCompiler.js:265:5)
at WebpackCompiler.processFilesForTarget (packages/webpack:webpack/plugin/WebpackCompiler.js:112:5)
```

**Comment by tomitrescak** [comment]
Doing `npm i esprima-fb` solves the issue, not sure what is the problem though.

**Comment by feit** [comment]
#133

**Comment by lyquocnam** [comment]
this serious bug for this awesome package, @eXon  so long not see :3

**Comment by lyquocnam** [comment]
try here https://github.com/thereactivestack/meteor-webpack/issues/150

**Comment by john-osullivan** [comment]
Ran into the same issue with the same library in the same circumstance (deploying to Meteor, ENOENT error on `esprima-fb`), tried running `npm i esprima-fb` and it resolved that error.  Same bug happened afterward with a different library, `autolinker`, but running `npm i autolinker` fixed that one as well.  No idea why it's behaving like that, but maybe it'll provide a useful clue for others.

**Comment by eXon** [comment]
I'm pretty sure if you update your React with the last NPM version it will work fine. One version of React was screwed up on Meteor for I don't know what reason. Let me know if not.
