### ISSUE TITLE
Looking for unexisting package uglify-js

### ISSUE THREAD

**Issue by gsabran** [thereactivestack/meteor-webpack#157]
When building, webpack looks for `uglify-js` in meteor folder, and there is no such thing:

```
Error: ENOENT, no such file or directory '/Users/me/.meteor/packages/meteor-tool/.1.3.2_3.rvtyg7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/uglify-js'
W20160504-22:53:48.778(-7)? (STDERR)     at Object.fs.lstatSync (fs.js:691:18)
W20160504-22:53:48.778(-7)? (STDERR)     at Object.realpathSync (fs.js:1279:21)
W20160504-22:53:48.778(-7)? (STDERR)     at webpack:///~/uglify-js/tools/node.js:21:1
W20160504-22:53:48.778(-7)? (STDERR)     at Array.map (/Users/me/.meteor/packages/es5-shim/.4.5.10.1kbbq1q++os+web.browser+web.cordova/npm/node_modules/es5-shim/es5-shim.js:466:33)
W20160504-22:53:48.778(-7)? (STDERR)     at Object.<anonymous> (webpack:///~/uglify-js/tools/node.js:20:1)
W20160504-22:53:48.779(-7)? (STDERR)     at Object.exports.SourceMapGenerator (webpack:///~/uglify-js/tools/node.js:249:1)
W20160504-22:53:48.779(-7)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap db49280a703ad1f53da9:23:1)
W20160504-22:53:48.779(-7)? (STDERR)     at Object.<anonymous> (webpack:///~/web-resource-inliner/src/html.js:8:1)
W20160504-22:53:48.779(-7)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap db49280a703ad1f53da9:23:1)
W20160504-22:53:48.779(-7)? (STDERR)     at Object.<anonymous> (webpack:///~/web-resource-inliner/src/inline.js:16:1)
```

I tried to install `uglify-js` in my project folder, but that doesn't change things. Should uglify be part of Meteor or is it that webpack should look for it somewhere else?

**Comment by eXon** [comment]
Any steps to reproduce or a git?

**Comment by gsabran** [comment]
Sure. I updated my repo from https://github.com/thereactivestack/meteor-webpack/issues/149 : https://github.com/gsabran/kickstart-meteor-react-flowrouter/tree/npm-module .
It's simply the kickstart repo, with the json loader package and another package loaded on the server side. Let me know if that's works fine on your end

**Comment by eXon** [comment]
```sh
meteor update
meteor remove react-runtime
meteor remove thereactivestack:blazetoreact
meteor add thereactivestack:blazetoreact
```
And now it should work fine. Let me know if it works.

**Comment by gsabran** [comment]
That did change things. (any insights of what happened?)

However the build is still failing, due to what might be a separated issue:

```
Error: ENOENT, no such file or directory 'node_modules/mimer/lib/data/mime.types'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at module.exports (webpack:///~/mimer/lib/data/parser.js:13:1)
    at Object.<anonymous> (webpack:///~/mimer/lib/exec.js:81:1)
    at webpack:///~/mimer/lib/exec.js:19:1
    at Object.<anonymous> (webpack:///~/mimer/lib/exec.js:29:1)
    at Object.splitDeviceRe (webpack:///~/mimer/lib/exec.js:83:1)
    at __webpack_require__ (webpack:/webpack/bootstrap a171cd219be855e0c7ee:23:1)
    at Object.__WEBPACK_AMD_DEFINE_ARRAY__ (webpack:///~/mimer/mimer.js:1:1)
    at __webpack_require__ (webpack:/webpack/bootstrap a171cd219be855e0c7ee:23:1)
```

I've looked into the mimer package. The error is thrown here: https://github.com/heldr/mimer/blob/master/lib/data/parser.js#L9
That is called from https://github.com/heldr/mimer/blob/master/lib/exec.js#L77

I'm not sure if this because webpack would change things related to path. I've added some logs and before throwing the error, `__dirname` is `'node_modules/mimer/lib/data'` and `process.cwd()` is `'/Users/me/kickstart-meteor-react-flowrouter/.meteor/local/build/programs/server'`

There is a file at `'/Users/me/kickstart-meteor-react-flowrouter/node_modules/mimer/lib/data/mime.types'`

**Comment by gsabran** [comment]
Let me know if you want a new issue for that

**Comment by eXon** [comment]
This is weird. On what OS are you?

**Comment by gsabran** [comment]
Macbook Pro, OS 10.11.4 Should not be very specific

**Comment by gsabran** [comment]
I've totally uninstalled and reinstalled node and meteor and node modules and the problem persists. I'm actually still getting the first error (can't find `uglify-js`) even after running

```
meteor update
meteor remove react-runtime
meteor remove thereactivestack:blazetoreact
meteor add thereactivestack:blazetoreact
```

**Comment by gsabran** [comment]
I've been able to reproduce the error as so:
- get a fresh Ubuntu instance (I've done it on AWS EC2)
- configure it to have port 3000 open, in addition to port 22 (for ssh). (On AWS you do so by adding a custom TCP rule in the security group, with port range being 3000)
- ssh to the instance and run:

``` shell
sudo apt-get update

# git
sudo apt-get -y install git

# node
curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
sudo apt-get install -y nodejs

# meteor
curl https://install.meteor.com/ | sh

git clone https://github.com/thereactivestack/kickstart-meteor-react-flowrouter.git
cd kickstart-meteor-react-flowrouter

npm install
npm install juice --save

echo "import juice from 'juice';" >> src/server.js
meteor

```

I then tried to run
```
meteor update
meteor remove react-runtime
meteor remove thereactivestack:blazetoreact
meteor add thereactivestack:blazetoreact
```

But that didn't change things.

**Comment by eXon** [comment]
Is this still a problem?
