### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by infacq** [thereactivestack/meteor-webpack#189]
I'm trying to load a loader for MapboxGL in my webpack.conf.js like this

```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    resolve: {
        extensions: ['', '.js', '.jsx'],
        alias: {
            webworkify: 'webworkify-webpack'
        }
    },
    module: {
        loaders: [
            {
                test: /\.json$/, 
                loader: 'json-loader'
            }, {
                test: /\.js$/,
                include: path.resolve('./node_modules/mapbox-gl-shaders/index.js'),
                loader: 'transform/cacheable?brfs'
            }
        ]
    },
    postLoaders: [{
        include: /node_modules\/mapbox-gl-shaders/,
        loader: 'transform',
        query: 'brfs'
    }],
    sassLoader: {
        includePaths: [path.resolve(__dirname, "./node_modules")]
    }
};
```

however this in not working due to error

```bash
W20160610-05:37:44.005(8)? (STDERR)           
W20160610-05:37:44.005(8)? (STDERR) /Users/infacq/Documents/sewa-copy/src/.meteor/local/build/programs/server/app/server.js:59
W20160610-05:37:44.006(8)? (STDERR)     import { ReactRouterSSR } from 'meteor/reactrouter:react-router-ssr';
W20160610-05:37:44.006(8)? (STDERR)     ^^^^^^
W20160610-05:37:44.006(8)? (STDERR) SyntaxError: Unexpected reserved word
W20160610-05:37:44.006(8)? (STDERR)     at /Users/infacq/Documents/sewa-copy/src/.meteor/local/build/programs/server/boot.js:278:30
W20160610-05:37:44.006(8)? (STDERR)     at Array.forEach (native)
W20160610-05:37:44.006(8)? (STDERR)     at Function._.each._.forEach (/Users/infacq/.meteor/packages/meteor-tool/.1.3.2_4.1kc6u63++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160610-05:37:44.006(8)? (STDERR)     at /Users/infacq/Documents/sewa-copy/src/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8 
```

am I doing it right?

**Comment by eXon** [comment]
Take a look at how Meteor Webpack package are made and you can make one for MapboxGL. They are not regular Webpack config files.
