### ISSUE TITLE
Error after upgrade to Meteor 1.3.3

### ISSUE THREAD

**Issue by feit** [thereactivestack/meteor-webpack#192]
packages/webpack:webpack/plugin/WebpackCompiler.js:197:10: Object [object Object] has no method 'existsSync'

**Comment by eXon** [comment]
Fixed in next released

**Comment by vladejs** [comment]
I still get errors on Meteor 1.3.3.1
```
 While processing files with webpack:webpack (for target web.browser):
   packages/webpack:webpack/plugin/WebpackCompiler.js:173:10: Object [object Object] has no method 'existsSync'
   at updateNpmPackages (packages/webpack:webpack/plugin/WebpackCompiler.js:173:10)
   at WebpackCompiler.processFilesForTarget (packages/webpack:webpack/plugin/WebpackCompiler.js:105:7)
```
