### ISSUE TITLE
Error requiring sinon in meteor test mode

### ISSUE THREAD

**Issue by PhilippSpo** [thereactivestack/meteor-webpack#196]
When I start the tests using `meteor test --driver-package dispatch:mocha-phantomjs` I get the following error when I try to import _sinon_:
```
➜  kickstart-meteor-react git:(master) ✗ meteor test --driver-package dispatch:mocha-phantomjs
[[[[[ Tests ]]]]]

=> Started proxy.
=> Started MongoDB.
W20160613-22:21:15.120(2)? (STDERR)
W20160613-22:21:15.122(2)? (STDERR) /Users/psporrer/.meteor/packages/meteor-tool/.1.3.2_4.3ref84++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160613-22:21:15.122(2)? (STDERR)             				throw(ex);
W20160613-22:21:15.122(2)? (STDERR)             				      ^
W20160613-22:21:15.299(2)? (STDERR) TypeError: Cannot call method 'call' of undefined
W20160613-22:21:15.300(2)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap d5000becdc165373c8ae:22:1)
W20160613-22:21:15.300(2)? (STDERR)     at Object.loadDependencies (webpack:///~/sinon/lib/sinon.js:20:1)
W20160613-22:21:15.300(2)? (STDERR)     at webpack:///~/sinon/lib/sinon.js:41:1
W20160613-22:21:15.300(2)? (STDERR)     at Object.<anonymous> (webpack:///~/sinon/lib/sinon.js:49:1)
W20160613-22:21:15.300(2)? (STDERR)     at Object.module.exports.module.deprecate (webpack:///~/sinon/lib/sinon.js:49:1)
W20160613-22:21:15.300(2)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap d5000becdc165373c8ae:22:1)
W20160613-22:21:15.300(2)? (STDERR)     at Object.<anonymous> (webpack:///src/TodoApp/server/publications.tests.js:4:1)
W20160613-22:21:15.300(2)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap d5000becdc165373c8ae:22:1)
W20160613-22:21:15.300(2)? (STDERR)     at webpackContext (webpack:/. ^\.\/.*$:38:1)
W20160613-22:21:15.300(2)? (STDERR)     at webpack:///WebpackTestRunner.js:15:1
=> Exited with code: 8
```
To easily reproduce this behaviour I have cloned the _kickstart-meteor-react_ repo and add a minimal tests that requires _sinon_.
To reproduce you just have to run `meteor test --driver-package dispatch:mocha-phantomjs`.

This somehow seems to be related to _sinon_, since there are no errors when using just _chai_.

**Comment by eXon** [comment]
Not sure what is the problem. Have you found a fix?

**Comment by PhilippSpo** [comment]
Haven't tried it since.
