### ISSUE TITLE
huge build time

### ISSUE THREAD

**Issue by IvanPortfolio** [thereactivestack/meteor-webpack#204]
It takes for me really slowly to build the project. I had the same on standart meteor build system, but webpack works for me much slowlier The project bulds really slowly it took me 35 minutes to build an app, and for a while to rebuild it. 

Project is a really small.

my package.json file 
`{
  "name": "hello",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "main": "server/startup.js",
  "browser": "client/main.js",
  "dependencies": {
    "dropzone": "*",
    "formidable": "^1.0.17",
    "material-ui": "*",
    "meteor-node-stubs": "~0.2.0",
    "react": "^15.0.1",
    "react-addons-pure-render-mixin": "^15.0.1",
    "react-addons-transition-group": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-if": "^2.0.5",
    "react-mounter": "^1.2.0",
    "react-router": "^2.3.0",
    "react-tap-event-plugin": "^1.0.0",
    "validate-obj": "^0.8.4"
  },
  "devDependencies": {
    "webpack": "^1.13.0",
    "webpack-hot-middleware": "^2.10.0",
    "url-loader": "^0.5.7",
    "file-loader": "^0.8.5",
    "style-loader": "^0.13.0",
    "css-loader": "^0.23.0",
    "extract-text-webpack-plugin": "^0.9.1",
    "json-loader": "^0.5.4",
    "babel": "^6.3.26",
    "babel-core": "^6.3.26",
    "babel-loader": "^6.2.0",
    "babel-preset-react": "^6.3.13",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-plugin-transform-decorators-legacy": "^1.3.2",
    "babel-plugin-add-module-exports": "^0.1.2",
    "babel-plugin-react-transform": "^2.0.0",
    "expose-loader": "^0.7.1",
    "react-transform-hmr": "^1.0.1",
    "react-transform-catch-errors": "^1.0.0",
    "redbox-react": "^1.2.0"
  }
}`

and meteor packages

`meteor-base            
mobile-experience  
 mongo                   
blaze-html-templates    
reactive-var           
jquery                 
tracker                
standard-minifier-css   
standard-minifier-js 
es5-shim               
react-meteor-data
accounts-password
accounts-facebook
accounts-twitter
accounts-google
natestrauser:font-awesome
service-configuration
session
polyroid:font-roboto
cfs:standard-packages
cfs:gridfs
less
nimble:restivus
alanning:roles
webpack:webpack
webpack:react`

the meteor version is 1.3.3
my hardware configuration is
i5
8gb ram
ssd
windows 10

**Comment by IvanPortfolio** [comment]
Sorry, my mistake. The meteor verion was 1.3.2.4
But when I`ve updated to version 1.3.3.1 I got this error on adding package

`C:\Users\ivank\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
            ^
Error: No metadata files found for isopack at: /C/Users/ivank/AppData/Local/.meteor/packages/webpack_webpack/1.3.3
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:514:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\ivank\AppData\Local\.meteor\packages\meteor-tool\1.3.3_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:513:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:448:20)
    at C:\tools\packaging\tropohouse.js:592:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:589:20)
    at C:\tools\project-context.js:738:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:737:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-context.js:736:13)
    at ProjectContext._downloadMissingPackages (C:\tools\tool-env\profile.js:283:16)
    at C:\tools\project-context.js:281:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:271:18)
    at C:\tools\project-context.js:263:12
    at C:\tools\tool-env\profile.js:283:16
    at time (C:\tools\tool-env\profile.js:305:10)
    at Function.run (C:\tools\tool-env\profile.js:500:14)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:262:13)
    at C:\tools\cli\commands-packages.js:2037:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands-packages.js:2036:27)
    at C:\tools\cli\main.js:1402:23`

**Comment by IvanPortfolio** [comment]
works fine on ubuntu

**Comment by menelike** [comment]
please take a look on https://github.com/meteor/meteor/issues/7008#issuecomment-227829312 

especially your babel modules will slow down the build process. first steps towards a better handling of node_modules have been done, but work is still in progress:

> Though there's definitely a lot more work to do here, I think we should take it up in Meteor 1.4 now that it's somewhat more tolerable in Meteor 1.3.4. 
*from https://github.com/meteor/meteor/issues/7008#issuecomment-227903243*

**Comment by gsabran** [comment]
(you can use three ` to better format your code, of use a gist) :)

**Comment by mzugn** [comment]
I haven't experienced any improvement with 1.3.4. When I change server code I get around 5-6 minute rebuilds. Client code naturally reloads quickly but Meteor stuff still kicks in and restarts the server in many cases, which hinders the convenience of hot reloading the client side. Actually doing a Meteor build for deployment takes around 30 minutes. I'd like to know if this is solvable or this is how Meteor development looks like today and we can't do anything about it.

I added some timers to WebpackCompiler.js and running the webpack part itself seems very fast, so what on earth is Meteor doing in the remaining 98% of the time?

**Comment by IvanPortfolio** [comment]
I deleted this packge because it does nothing. Seems to be meteor issue. And it is. The promise to improve it in1.4.  Event on really big projects with webpack but without Meteor rebuild time is 5-6s. And for Meteor it is minutes

**Comment by IvanPortfolio** [comment]
Works much better on linux but it is still very slowly

**Comment by eXon** [comment]
I would rather keep only specific issues open. If you have tweaks that you think can improve the build time, I'll take a look at them.
