### ISSUE TITLE
declaring export default on same line as definition throws errors

### ISSUE THREAD

**Issue by teebszet** [thereactivestack/meteor-webpack#217]
is this expected? I'm unable to declare export default on the same line as the function that is defined.

I end up having to refactor all these definitions to clear errors thrown like:

```
/Users/user/.meteor/packages/meteor-tool/.1.3.3_1.1lsjhed++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
                    throw(ex);
                          ^
ReferenceError: storeStagedRoutes is not defined
    at Object.defineProperty.value (webpack:///imports/startup/server/wayfinder/storeStagedRoutes.js:39:1)
    at __webpack_require__ (webpack:/webpack/bootstrap fbfc5b3c6c400d96bbc2:22:1)
    at Object.module.exports (webpack:///imports/startup/server/wayfinder/storeNodesAndEdges.js:6:1)
    at __webpack_require__ (webpack:/webpack/bootstrap fbfc5b3c6c400d96bbc2:22:1)
    at Object.defineProperty.value (webpack:///imports/startup/server/index.js:6:1)
    at __webpack_require__ (webpack:/webpack/bootstrap fbfc5b3c6c400d96bbc2:22:1)
    at Object.defineProperty.value (webpack:///server/main.js:1:1)
    at __webpack_require__ (webpack:/webpack/bootstrap fbfc5b3c6c400d96bbc2:22:1)
    at Object.defineProperty.value (webpack:/webpack/bootstrap fbfc5b3c6c400d96bbc2:39:1)
    at webpack:/webpack/bootstrap fbfc5b3c6c400d96bbc2:39:1
```

where storeStagedRoutes.js has:

```
export default storeStagedRoutes = () => {};
```

I found that the fix for this is exporting the default on a separate line like:

```
const storeStagedRoutes = () => {};
export default storeStagedRoutes;
```

Is this expected behaviour? I don't think this is a requirement when using a pure webpack build (without webpack:webpack and meteor)

Also, the same issue occurs when using require rather than import.

**Comment by eXon** [comment]
When using a default export, you can't name it like this. It is normal ES6.
