### ISSUE TITLE
Server vs client

### ISSUE THREAD

**Issue by niallobrien** [thereactivestack/meteor-webpack#22]
Am I correct in saying that I can have a different webpack config for the server vs the client?
If so, how do I go about this? Thanks.

**Comment by imkost** [comment]
Yes, you can have different configs for server and client. Just place server's config to `server` folder and client's config to `client`.

Check out this project https://github.com/thereactivestack/kickstart-simple. It has example of webpack configs. Or this one https://github.com/imkost/mercury/tree/master/website (it's a fork of kickstart-simple project with more plain file structure)

**Comment by niallobrien** [comment]
Thanks, any ideas as to why I might be getting the below error? Thanks in advance.
```
=> Started proxy.
=> Started MongoDB.
Installing NPM dependencies for the web bundle...
webpack built 70a0a22be92f7548c834 in 3491ms -
Installing NPM dependencies for the server bundle...
=> Errors prevented startup:

   While processing files with webpack:webpack (for target os.osx.x86_64):

   /Users/niall/.meteor/packages/webpack_webpack/.0.2.9.66ogwv++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:86:10:
   Path doesn't exist '/memory/webpack/server.js'
   at MemoryFileSystem.readFileSync
   (/Users/niall/.meteor/packages/webpack_webpack/.0.2.9.66ogwv++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:86:10)
   at compile (plugin/WebpackCompiler.js:392:19)
   at runWebpack (plugin/WebpackCompiler.js:180:5)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:69:5)
```
