### ISSUE TITLE
Error related to memory-fs

### ISSUE THREAD

**Issue by niallobrien** [thereactivestack/meteor-webpack#23]
Hi, I'm receiving the below error when trying to run my project (I'm not using React like in most examples).

Any advice would be appreciated.

```
=> Started proxy.
=> Started MongoDB.
Installing NPM dependencies for the web bundle...
webpack built 70a0a22be92f7548c834 in 3491ms -
Installing NPM dependencies for the server bundle...
=> Errors prevented startup:

   While processing files with webpack:webpack (for target os.osx.x86_64):

   /Users/niall/.meteor/packages/webpack_webpack/.0.2.9.66ogwv++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:86:10:
   Path doesn't exist '/memory/webpack/server.js'
   at MemoryFileSystem.readFileSync
   (/Users/niall/.meteor/packages/webpack_webpack/.0.2.9.66ogwv++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/memory-fs/lib/MemoryFileSystem.js:86:10)
   at compile (plugin/WebpackCompiler.js:392:19)
   at runWebpack (plugin/WebpackCompiler.js:180:5)
   at WebpackCompiler.processFilesForTarget (plugin/WebpackCompiler.js:69:5)
```

**Comment by niallobrien** [comment]
Here's my work-in-progress repo: https://github.com/niallobrien/vue-webpack-meteor-example

**Comment by eXon** [comment]
It might be due to the fact that you have no server-side code. Have you tried adding something?

**Comment by niallobrien** [comment]
I just moved some code around and it's still the same.

**Comment by eXon** [comment]
You'l need to set an entry file for the server.

**Comment by niallobrien** [comment]
Perfect, thank you. Got it working. :)
