### ISSUE TITLE
problem with npm package ENOENT: ... scandir

### ISSUE THREAD

**Issue by rkstar** [thereactivestack/meteor-webpack#238]
i've built an npm package that works fine on vanilla node projects and with regular meteor 1.4 projects, but not with `webpack:webpack`.

when i import my npm package, i get this error:
```
W20160726-09:04:25.699(-4)? (STDERR) /Users/rkstar/.meteor/packages/meteor-tool/.1.4.0.5hn0q8++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20160726-09:04:25.700(-4)? (STDERR) 						throw(ex);
W20160726-09:04:25.701(-4)? (STDERR) 						^
W20160726-09:04:25.701(-4)? (STDERR) 
W20160726-09:04:25.701(-4)? (STDERR) Error: ENOENT: no such file or directory, scandir '/Users/rkstar/dev/projects/crate/microservices/test/.meteor/local/build/programs/server/node_modules/whistlepunk/src/adapters'
W20160726-09:04:25.701(-4)? (STDERR)     at Error (native)
W20160726-09:04:25.701(-4)? (STDERR)     at Object.fs.readdirSync (fs.js:808:18)
W20160726-09:04:25.702(-4)? (STDERR)     at getAdapters (webpack:///~/whistlepunk/src/configParser.js:19:1)
W20160726-09:04:25.702(-4)? (STDERR)     at Object.<anonymous> (webpack:///~/whistlepunk/src/configParser.js:9:1)
W20160726-09:04:25.702(-4)? (STDERR)     at Object.<anonymous> (webpack:///~/whistlepunk/src/configParser.js:88:1)
W20160726-09:04:25.702(-4)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap 6c03425500f2b4f770a4:22:1)
W20160726-09:04:25.702(-4)? (STDERR)     at setup (webpack:///~/whistlepunk/src/index.js:11:1)
W20160726-09:04:25.703(-4)? (STDERR)     at module.exports (webpack:///~/whistlepunk/src/log.js:55:1)
W20160726-09:04:25.703(-4)? (STDERR)     at Object.VERSION (webpack:///~/whistlepunk/src/index.js:18:1)
W20160726-09:04:25.703(-4)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap 6c03425500f2b4f770a4:22:1)
=> Exited with code: 1
```

i've made a repo with the initial `webpack:webpack` setup here:
https://github.com/rkstar/test-meteor-webpack

and i've made another repo with the default meteor 1.4 setup here:
https://github.com/rkstar/test-meteor-no-webpack

if you clone them and `meteor npm install` then run `meteor` you'll see that the vanilla meteor one works, but webpack repo throws.

NOTE: the only differences from the initial webpack setup is that i had to add an `IgnorePlugin` for `vertx` in my config.  other than that, the only thing i'm doing is importing `wabbit` in both projects.

any idea what's happening here?

**Comment by seanjsong** [comment]
I know exactly what's happening here, because I have come across the same problem. But I don't have a solution.

Let's first inspect your stack trace, have a look at https://github.com/LeanKit-Labs/whistlepunk/blob/v0.3.3/src/configParser.js#L16:

```
	var adapterPath = path.resolve( __dirname, "./adapters" );
	var files = fs.readdirSync( adapterPath );
```

Problem is caused because ``__dirname`` is replaced by webpack to a relative path, have a look at https://github.com/webpack/webpack/blob/v1.12.14/lib/NodeStuffPlugin.js#L59:

```
		setModuleConstant("__dirname", function(module) {
			return path.relative(context, module.context);
		});
```

``context`` is ``CWD``(https://github.com/thereactivestack/meteor-webpack/blob/master/packages/webpack/plugin/WebpackCompiler.js#L95). Suppose you run ``meteor`` at your project root directory, and ``node_modules`` is a subdirectory, then ``module.context`` relative to ``context`` should be ``node_modules/whistlepunk/src``.

Just now we talked about build time. However, run time is a different story. When server is started, ``process.cwd()`` becomes ``.meteor/local/build/programs/server``, when ``fs.readdirSync`` is called, it takes the argument ``path.resolve( __dirname, "./adapters" )`` which evaluates to ``node_modules/whistlepunk/src/adapters``, resolves it to an absolute path which is ``/Users/rkstar/dev/projects/crate/microservices/test/.meteor/local/build/programs/server/node_modules/whistlepunk/src/adapters`` in your case. But the target directory isn't there! The directory should actually be /Users/rkstar/dev/projects/crate/microservices/test/.meteor/local/build/programs/server/```npm```/node_modules/whistlepunk/src/adapters, note the extra ``npm`` in the path! That's how the server code is bundled with the current version of webpack:webpack.

@eXon All npm packages that accesses ```__dirname``` or ```__filename``` will have this problem. This is a general problem. Please prioritize and fix it. Many thanks!

**Comment by jdanilov** [comment]
Also happening for me. This prevents using libraries such as googleapis.
