### ISSUE TITLE
Deploy to modulus.io fails

### ISSUE THREAD

**Issue by vladejs** [thereactivestack/meteor-webpack#256]
Hello, I have several projects hosted on modulus. All I do is bundle my projects in a `.zip` and upload them to the platform. Modulus does the rest ( realize which meteor version to use, which packages to install etc ). 

With a project that uses webpack, modulus fails with this output:
 
```
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v4.4.7 (npm v3.10.5)
Initializing Meteor environment.
Using METEOR@1.3.3.1.
Demeteorizing application...
TypeError: undefined is not a function
    at config (eval at readPackageConfig (packages/webpack:webpack/plugin/WebpackCompiler.js:304:28), <anonymous>:57:18)
    at packages/webpack:webpack/plugin/WebpackCompiler.js:325:26
    at Array.forEach (native)
    at Object.load (packages/webpack:webpack/plugin/WebpackCompiler.js:323:15)
    at WebpackCompiler.processFilesForTarget (packages/webpack:webpack/plugin/WebpackCompiler.js:131:13)
    at __bottom_mark__ (/tools/utils/parse-stack.js:64:14)
    at /tools/isobuild/compiler-plugin.js:188:13
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at /tools/isobuild/compiler-plugin.js:177:22
    at Function.time (/tools/tool-env/profile.js:305:10)
    at /tools/isobuild/compiler-plugin.js:176:15
    at Function._.each._.forEach (/mnt/home/.meteor/packages/meteor-tool/.1.3.3_1.wzhjxc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at CompilerPluginProcessor.runCompilerPlugins (/tools/isobuild/compiler-plugin.js:166:7)
    at ClientTarget._runCompilerPlugins (/tools/isobuild/bundler.js:913:22)
    at /tools/isobuild/bundler.js:693:34
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ClientTarget.make (/tools/isobuild/bundler.js:687:18)
    at /tools/isobuild/bundler.js:2533:14
    at /tools/isobuild/bundler.js:2622:20
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/home/.meteor/packages/meteor-tool/.1.3.3_1.wzhjxc++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:79:11)
    at /tools/isobuild/bundler.js:2621:7
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2514:31)
    at buildCommand (/tools/cli/commands.js:896:30)
    at Command.main.registerCommand._.extend.name [as func] (/tools/cli/commands.js:776:12)
    at /tools/cli/main.js:1402:23
Errors prevented bundling:
While processing files with webpack:webpack (for target web.browser):
error: Can't load npm module
'/mnt/input/node_modules/extract-text-webpack-plugin' from
packages/webpack_npmworkaround.js. Check your Npm.depends().
src/index.js: Entry module not found: Error: Cannot resolve module 'babel' in
/mnt/input
resolve module babel in /mnt/input

While processing files with fourseven:scss (for target web.browser):
/src/client/styles/bootstrap-custom.scss: Scss compiler error: File to import:
{}/node_modules/bootstrap-sass/assets/stylesheets/bootstrap/variables not found
in file: /mnt/input/{}/src/client/styles/bootstrap-custom.scss


While processing files with webpack:webpack (for target os.linux.x86_64):
src/main.js: Entry module not found: Error: Cannot resolve module 'babel' in
/mnt/input
resolve module babel in /mnt/input

Conversion failed.
Build attempt failed, attempting again.
Starting build.
Creating directories for build environment.
Downloading source.
Executing build.
Now using node v4.4.7 (npm v3.10.5)
Initializing Meteor environment.
Using METEOR@1.3.3.1.
Demeteorizing application...
Log Stream Disconnected
```

Does someone know a workaround to fix this?

**Comment by eXon** [comment]
Not sure what Demeteorizing application is doing. Do you have more infos on this?

**Comment by vladejs** [comment]
Demeteorizer from modulus does `meteor build` and `npm install`, it works with most apps, but seems like it does not know how to handle the fact that webpack takes over on the build system. 

I uploaded the source code, not sure if it works by doing myself `modulus deploy` or uploading a demeteorized app in local.

**Comment by fiveisprime** [comment]
@eXon Demeteorizer calls `$ meteor build --architecture os.linux.x86_64 --server localhost --server-only` then modifies the generated package.json file to make sure the correct version of node is specified. Nothing incredibly special there.

Based on that, you should be able to repro this by running meteor build if that helps.

**Comment by vladejs** [comment]
Is there a workaround for this?
