### ISSUE TITLE
Error on command - meteor add webpack:webpack

### ISSUE THREAD

**Issue by dulguun0225** [thereactivestack/meteor-webpack#264]
I'm getting following error on command `meteor add webpack:webpack`. I'm on lubuntu 16.0.1 i386 wmware player virtual machine. Seems like it has something to do with `fsevents` npm package.

```
 => Errors while adding packages:

While loading package webpack:webpack@1.3.4:
error: Command failed:
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
node-pre-gyp ERR! Tried to download:
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-linux-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and
node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError
(/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/which/which.js:14:12)
gyp ERR! stack     at F
(/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/which/which.js:69:19)
gyp ERR! stack     at E
(/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/which/which.js:81:29)
gyp ERR! stack     at
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/which/which.js:90:16
gyp ERR! stack     at
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/isexe/index.js:44:5
gyp ERR! stack     at
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/node-gyp/bin/node-gyp.js"
"build" "--fallback-to-build"
"--module=/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32/fse.node"
"--module_name=fse"
"--module_path=/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32"
gyp ERR! cwd
/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute
'/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/node-gyp/bin/node-gyp.js
build --fallback-to-build
--module=/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32/fse.node
--module_name=fse
--module_path=/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
(/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.0-34-generic
node-pre-gyp ERR! command
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/.bin/node-pre-gyp"
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/npm-debug.log
node-pre-gyp ERR! Tried to download:
https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v46-linux-ia32.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and
node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError
(/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/which/which.js:14:12)
gyp ERR! stack     at F
(/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/which/which.js:69:19)
gyp ERR! stack     at E
(/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/which/which.js:81:29)
gyp ERR! stack     at
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/which/which.js:90:16
gyp ERR! stack     at
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/isexe/index.js:44:5
gyp ERR! stack     at
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.4.0-34-generic
gyp ERR! command
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/node-gyp/bin/node-gyp.js"
"build" "--fallback-to-build"
"--module=/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32/fse.node"
"--module_name=fse"
"--module_path=/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32"
gyp ERR! cwd
/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute
'/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node
/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/node-gyp/bin/node-gyp.js
build --fallback-to-build
--module=/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32/fse.node
--module_name=fse
--module_path=/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents/lib/binding/Release/node-v46-linux-ia32'
(1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous>
(/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit
(internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.0-34-generic
node-pre-gyp ERR! command
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/lib/node_modules/.bin/node-pre-gyp"
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd
/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/node_modules/fsevents
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.29
node-pre-gyp ERR! not ok 

npm ERR! Linux 4.4.0-34-generic
npm ERR! argv
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/node"
"/home/usr/.meteor/packages/meteor-tool/.1.4.1.1smi08j++os.linux.x86_32+web.browser+web.cordova/mt-os.linux.x86_32/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.14 install script 'node-pre-gyp install
--fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/home/usr/.meteor/packages/webpack_webpack/.1.3.4.9o7wug++os.linux.x86_32+web.browser+web.cordova/plugin.webpack_webpack.os.linux.x86_32/npm/node_modules/meteor/webpack_webpack/node_modules/.temp-erdzya/npm-debug.log
```

**Comment by eXon** [comment]
There is some weird stuff with NPM on Meteor 1.4. I'll try to investigate when I have some time.

**Comment by jadus** [comment]
any update about this ?

**Comment by dulguun0225** [comment]
In general Meteor has some weird hiccups on Windows, might be related to Meteor issue.
