### ISSUE TITLE
Cannot run webpack:webpack@=1.3.3 with Meteor 1.4.1

### ISSUE THREAD

**Issue by ceonnel** [thereactivestack/meteor-webpack#265]
After Meteor 1.4.1 update, Meteor startup is prevented by error:
`Cannot find module 'arr-flatten'`
I tried to install `arr-flatten` on local and global, but it doesn't help.
I can't update webpack to version 1.3.4 because: #257 

Stacktrace:

`Error: Cannot find module 'arr-flatten'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (%LOCALAPP%\.meteor\packages\webpack_webpack\1.3.3\plugin.webpack_webpack.os\npm\node_modules\meteor\webpack_webpack\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\arr-diff\index.js:10:15)`

Windows 10 64-bit

## Updated

I found that deep npm dependencies is corrupted in `webpack:webpack@=1.3.3`
In `%LOCALAPP%l\.meteor\packages\webpack_webpack\1.3.3\plugin.webpack_webpack.os\npm\node_modules\meteor\webpack_webpack\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\arr-diff\node_modules\arr-flatten`
i found just LICENSE file, but no index.js.
I tried manually add index.js file and run meteor again.
`arr-flatten` module now is found, but problem appear in another module `fill-range`

```
webpack built 2cd5c8abefca67d36a25 in 17366ms-
module.js:327
    throw err;
    ^

Error: Cannot find module 'fill-range'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (%LOCALAPP%\.meteor\packages\webpack_webpack\1.3.3\plugin.webpack_webpack.os\npm\node_modules\meteor\webpack_webpack\node_modules\webpack\node_modules\watchpack\node_modules\chokidar\node_modules\anymatch\node_modules\micromatch\node_modules\braces\node_modules\expand-range\index.js:10:12)
```
In `...\expand-range` directory, node_modules folder is not exists at all.

When I try to create `node_modules/fill-range` folder manually I get error:
```
The file names(s) would be too long for the destination folder. You must shorten the file name and try again, o try a location has a shorter path.
```
Seems like is a problem with "too long paths" in Windows. But how can I solve it?

**Comment by eXon** [comment]
Uh looks like some weird stuff. I'll try to debug this when I have some time.

**Comment by jagarcia29** [comment]
Did you ever find a solution? I'm having the same issue

**Comment by ceonnel** [comment]
My solution: Windows => Linux.
