### ISSUE TITLE
Multiple Code splits for js and css

### ISSUE THREAD

**Issue by ferhtgoldaraz** [thereactivestack/meteor-webpack#27]
How would you go about having an admin entry point, with dependencies only
loaded when certain requirements are met (authentification for example)?

I'm having issues trying to make the css work. (btw i'm not using react).

I would like to use the plugin 'extract-text-webpack-plugin'. It would be
used to generate a number of CSS bundles, so that admin CSS only loads if
the admin view loads. Loading all the CSS would not be an option, since,
in a not-so-distant future the admin area will include CSS edition (different
users would have different, user-generated, CSS files).

For now, I only want to make two CSS bundles, one for the public side and one
admin area. I'm using `FlowRouter` and `require.ensure`, and that works as
expected, no problem there. I can even load CSS with the `style-loader` and
the `css-loader`.

The issue I raise is that each "route" can potentially require a lot of
CSS, and each one of them is being inserted to the page one by one. This
triggers a reflow and repaint cycle, and I don't know if it also triggers
what number of server roundtrips and CSS processing by the loaders.

I want to simply bundle all CSS for one route in one CSS, and all the CSS for
another route in another CSS, at development time, and simply `require` one
file for each route.

(As a side note, I'm kinda forced to add link stylesheet nodes instead of
stylesheet tags due to some CSP Headers that are probably gonna be
unavoidable.)

I'm having some errors with 'extract-text-webpack-plugin', I don't know if
it is the webpack version, or related to some hard-coded `output` properties,
or something else. I wouldn't know really how to tell webpack where to save
the bundles, or with what name.

The documentation of the plugin says that:

> The ExtractTextPlugin generates an output file per entry, so you must use
> [name], [id] or [contenthash] when using multiple entries.

When I try to pass an object with two entries to the `entry` config property,
everything breaks hard. The errors are too long to post here. I've tried to
trick the script into working by doing weird thing to the name of what would
hopefully be the ouptut bundle, but all of them have also failed.

I can offer the simplest scenario that also triggers an error, but an almost
legible one.

Here is my webpack.conf.js (it's the client's)

```js
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
    entry: './entry.js',
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                query: { stage: 0 },
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader')
            },
            {
                test: /\.(?:png|jpe?g)(?:\?.*)?$/,
                loader: 'url?limit=8182'
            },
            {
                test: /\.(?:svg|ttf|woff|eot)(?:\?.*)?$/,
                loader: 'file'
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('./wtf.import.css')
    ]
};
```

Here is my router file, right now it's the only file that does anything, were
all the requires are.

```js
FlowRouter.route('/', {
    action: function() {
        var data = require('Normal/test1.import');
        console.log(data);
        // BlazeLayout.render('mainLayout', {content: 'home'});
    }
});

// -----

FlowRouter.route('/admin', {
    action: function() {

        require.ensure(['Normal/test2.import'], function(require) {

            var data = require('Normal/test2.import');
            console.log(data);
            // BlazeLayout.render('mainLayout', {content: 'admin'});

        }, 'admin');
    }
});
```

And here is my errored output (note that [12] **failed**):

```bash
❯ meteor
[[[[[ ~/src/meteor/webpack/webpack-handcrafted/app ]]]]]

=> Started proxy.
=> Started MongoDB.
Installing NPM dependencies for the web bundle...
webpack built 1c71ebd3848a811ccb7f in 1691ms \
Hash: 1c71ebd3848a811ccb7f
Version: webpack 1.12.2
Time: 1691ms
       Asset     Size  Chunks       Chunk Names
      web.js  46.7 kB       0       main
    1.web.js  1.15 kB       1       admin
  web.js.map  55.9 kB       0       main
1.web.js.map  2.04 kB       1       admin
chunk    {0} web.js, web.js.map (main) 21.8 kB [rendered]
    [0] multi main 40 bytes {0} [built]
    [1] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/client.js?path=http://localhost:3500/__webpack_hmr 3.27 kB {0} [built]
    [2] (webpack)/buildin/module.js 251 bytes {0} [built]
    [3] ./.meteor/local/webpack-npm/~/querystring/index.js 127 bytes {0} [built]
    [4] ./.meteor/local/webpack-npm/~/querystring/decode.js 2.4 kB {0} [built]
    [5] ./.meteor/local/webpack-npm/~/querystring/encode.js 2.09 kB {0} [built]
    [6] ./.meteor/local/webpack-npm/~/strip-ansi/index.js 161 bytes {0} [built]
    [7] ./.meteor/local/webpack-npm/~/ansi-regex/index.js 135 bytes {0} [built]
    [8] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/client-overlay.js 883 bytes {0} [built]
    [9] ./.meteor/local/webpack-npm/~/webpack-hot-middleware/process-update.js 2.93 kB {0} [built]
   [10] ./client/entry.js 82 bytes {0} [built]
   [11] ./client/router.js 553 bytes {0} [built]
   [12] ./modules/Normal/test1.import.css 1.04 kB {0} [built] [failed]
   [13] ./.meteor/local/webpack-npm/~/css-loader!./modules/Normal/test1.import.css 227 bytes {0} [built]
   [14] ./.meteor/local/webpack-npm/~/css-loader/lib/css-base.js 1.51 kB {0} [built]
   [15] ./.meteor/local/webpack-npm/~/style-loader/addStyles.js 6.09 kB {0} [built]
chunk    {1} 1.web.js, 1.web.js.map (admin) 1.27 kB {0} [rendered]
   [16] ./modules/Normal/test2.import.css 1.04 kB {1} [built]
   [17] ./.meteor/local/webpack-npm/~/css-loader!./modules/Normal/test2.import.css 226 bytes {1} [built]

ERROR in ./modules/Normal/test1.import.css
Module build failed: Error: Parameter 'dependency' must be a Dependency
    at Compilation.process [as _addModuleChain] (/Users/Fer/.meteor/packages/webpack_webpack/.0.3.1.yhwpo2++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/webpack/lib/Compilation.js:347:9)
    at Compilation.process [as addEntry] (/Users/Fer/.meteor/packages/webpack_webpack/.0.3.1.yhwpo2++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/webpack/lib/Compilation.js:423:7)
    at SingleEntryPlugin.<anonymous> (/Users/Fer/src/meteor/webpack/webpack-handcrafted/app/.meteor/local/webpack-npm/node_modules/webpack/lib/SingleEntryPlugin.js:22:15)
    at Compiler.applyPluginsParallel (/Users/Fer/.meteor/packages/webpack_webpack/.0.3.1.yhwpo2++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/webpack/node_modules/tapable/lib/Tapable.js:107:14)
    at Compiler.compile (/Users/Fer/.meteor/packages/webpack_webpack/.0.3.1.yhwpo2++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/webpack/lib/Compiler.js:394:7)
    at Compiler.runAsChild (/Users/Fer/.meteor/packages/webpack_webpack/.0.3.1.yhwpo2++os+web.browser+web.cordova/plugin.webpack_webpack.os/npm/webpack_webpack/node_modules/webpack/lib/Compiler.js:203:7)
    at Object.module.exports.pitch (/Users/Fer/src/meteor/webpack/webpack-handcrafted/app/.meteor/local/webpack-npm/node_modules/extract-text-webpack-plugin/loader.js:81:18)
Installing NPM dependencies for the server bundle...
=> Started your app.

=> App running at: http://localhost:3000/
```

Even so, that stack trace is too much for me.

Should I consider running a second script (go back to gulp or run a seccond
webpack) just to build the CSS bundles? Is there some other webpack trick I
could use? Does anybody know if there's some meteor way/package for simply
having different CSS bundles, not all of them sent to the client?

Really hope there's some known solution for this. It would be awesome to avoid
multiple meteor instances, since we may end up having more scenarios where
code needs to be segregated in a similar way.

Apologies for the long post, thanks for everything.

**Comment by ferhtgoldaraz** [comment]
By the way, this project is extremely awesome :)

**Comment by eXon** [comment]
You should check the [kickstart-hugeapp](https://github.com/thereactivestack/kickstart-hugeapp).

It does code splitting for the admin section. It will not be loaded until you access the section.

This is doing code splitting for JS. Because CSS is bundled with React components (requiring css), it also split the CSS in the js file. Let me know if you this answer your question.

**Comment by ferhtgoldaraz** [comment]
I will look into it more closely.

Does react components handle the css requires? a single bundle with what would be needed hopefully? (static analisis)

That's abit what I'm looking for. I would go with react if it helped solve this issue (would have to learn it though)

**Comment by ferhtgoldaraz** [comment]
Im finding out that react uses inline styles. Is this the only way? Our CSP Headers are going to prohibit me from using inline anything. Not styles, not eval, not Function, nothing.

**Comment by ferhtgoldaraz** [comment]
I don't see react as having the styling problems solved enough for my needs. I'm actually a stylus guy, and like things like Atomic Design, BEM, Webpack's :local pseudo class, etc. Don't really want to be limited to stylesheets or inline styles anyway, and have already developed some patterns to solve [vjeaux's](http://blog.vjeux.com/2014/javascript/react-css-in-js-nationjs.html) concerns.

Thanks anyway, will keep trying. If I find apattern to bundle CSS without too much link addition that's good enough (or anyone really) I'll post it here.

If you think that the issue is solved for the more general use cases, you can close this.

**Comment by genyded** [comment]
@ferhtgoldaraz it may be overkill for what you need... but [Radium](https://github.com/FormidableLabs/radium) is sort of an inline styles on steroids for React. I haven't used it, but came across it at some point and tought it may be worth a look when I get a breather.

**Comment by ferhtgoldaraz** [comment]
Thanks. I'll look into it and fight for inline styles as a viable option.

**Comment by ferhtgoldaraz** [comment]
I'm closing this, as it seems react solves this well enough for people using this awesome project.

**Comment by ferhtgoldaraz** [comment]
I ended up using style-loader's `style/useable` feature, and Using [fastdom](https://github.com/wilsonpage/fastdom), specifically `fastdom.write`, to wrap the `someStyle.use` calls.

I still lack sourcemaps, and It still uses stylesheet tags. but it's the closest I can get without sacrificing anything.

**Comment by ferhtgoldaraz** [comment]
Actually, passing the `?sourcemap` option to webpack's `css-loader` gave both sourcemaps and link nodes insted of style ones (to a blob file).

Just in case someone ends up finding this useful
