### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'node_modules/mime/types/mime.types'

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [thereactivestack/meteor-webpack#279]
Hi! I'm trying to use this package
https://github.com/Automattic/knox
But looks like it depends on "mime" package... Even though the file node_modules/mime/types/mime.types exists, I get this error on the console when the server is built:
```
 Error: ENOENT: no such file or directory, open 'node_modules/mime/types/mime.types'
W20160920-12:34:45.445(-3)? (STDERR)     at Error (native)
W20160920-12:34:45.446(-3)? (STDERR)     at Object.fs.openSync (fs.js:549:18)
W20160920-12:34:45.446(-3)? (STDERR)     at Object.fs.readFileSync (fs.js:397:15)
W20160920-12:34:45.446(-3)? (STDERR)     at Mime.load (webpack:///~/mime/mime.js:57:1)
W20160920-12:34:45.446(-3)? (STDERR)     at Object.<anonymous> (webpack:///~/mime/mime.js:93:1)
W20160920-12:34:45.447(-3)? (STDERR)     at Object.<anonymous> (webpack:///~/mime/mime.js:114:1)
W20160920-12:34:45.447(-3)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap 64cdfcea6600f59fc6a6:22:1)
W20160920-12:34:45.447(-3)? (STDERR)     at Object.<anonymous> (webpack:///~/knox/lib/client.js:23:1)
W20160920-12:34:45.447(-3)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap 64cdfcea6600f59fc6a6:22:1)
W20160920-12:34:45.447(-3)? (STDERR)     at Object.<anonymous> (webpack:///~/knox/lib/index.js:16:1)
```

Is this related to webpack?

**Comment by seanjsong** [comment]
I guess this is the same problem as #238
