### ISSUE TITLE
Application not hitting breakpoints in Chrome on page load

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/meteor-webpack#74]
Hi, I am not sure whether this is the cause of a new way the webpack is packing files, but I no longer can put breakpoints into e.g. "render" method as it is never hit on page load. These breakopints are only hit on subsequent clicks in the application, when that component is rendered. Before, I was able to do it. Am I the only one here? The only way to have breakpoint hit in "render" is to manually type in "debugger" command. No biggie here, but I am curious.

**Comment by eXon** [comment]
I bet it is because of the change I made on the way we generate the source map. It was way too slow.

Try to set `devtool` to `"source-map"` in your webpack.json file and restart the app. If it works, it is because of that. It hits too much the build time for being the default but at least you have the choice to change it :)

**Comment by tomitrescak** [comment]
@eXon I forgot to reply, but please do not close this as it is quite an issue for me :/ I tried setting this in webpack.json

```
{
    "devTool": "source-map"
}
```

but no luck ;( The breakpoints are not hit. I have to always manually set the "debugger" command if I want the breakpoint to be hit. Any advice? Thanks.

**Comment by tomitrescak** [comment]
@exon since one of the latest releases this is what I see in the debug console:

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at TextEditorTabs.trigger (eval at <anonymous> (http://localhost:3500/assets/web.js:5147:2), <anonymous>:38:57)
    at TextEditorTabs.triggerTabsChanged (eval at <anonymous> (http://localhost:3500/assets/web.js:5177:2), <anonymous>:129:18)
    at TextEditorTabs.initTabs (eval at <anonymous> (http://localhost:3500/assets/web.js:5177:2), <anonymous>:85:18)
    at new TextEditorTabs (eval at <anonymous> (http://localhost:3500/assets/web.js:5177:2), <anonymous>:44:15)
    at new TabbedTextEditorModel (eval at <anonymous> (http://localhost:3500/assets/web.js:5171:2), <anonymous>:31:21)
    at composer (eval at <anonymous> (http://localhost:3500/assets/web.js:5111:2), <anonymous>:31:17)
    at Container._subscribe (eval at <anonymous> (http://localhost:3500/assets/web.js:1687:2), <anonymous>:155:24)
    at new Container (eval at <anonymous> (http://localhost:3500/assets/web.js:1687:2), <anonymous>:103:15)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:3000/packages/react-runtime-dev.js?cb960f7740531120074dfc77190e4421dc60a3a3:8158:18)
    at wrapper [as mountComponent] (http://localhost:3000/packages/react-runtime-dev.js?cb960f7740531120074dfc77190e4421dc60a3a3:15201:21) undefined
```

It is really difficult now to debug the application as all points to web.js is there any way I can recuperate the lines of code?

**Comment by jbbr** [comment]
I can confirm this issue. Unfortunately setting `"devtool": "source-map"` didn't work for me either (Note: I've tried lowercase `devtool` as that's how its expected in webpack config, inconsistent but that's how it is...)

The problem: meteor-webpack does not use "devtool" value from webpack.json. I fixed this in PR #127 

Setting `devtool` to `source-map` does fix this issue for me! I can add breakpoints directly in render() and also events and they are handled correctly.

Unfortunately breakpoints in server code do not work correctly... Looks as if there is still a source-map problem for server code. I think I should open an extra issue for that...

**Comment by tomitrescak** [comment]
@jbbr am a bit confused. You say that it did not work for you and then that it did. ... Soooooo ... what did you do to fix it? I tried setting "devtool": "source-map" and nothing. Please let me know.

**Comment by tomitrescak** [comment]
Ah, maybe I get it ;) With your PR life will be peachy! Is that correct? ;)

**Comment by jbbr** [comment]
Sorry I agree that my comment is a bit confusing.
But yes, you are right. 
Currently meteor-webpack ignores the `devtool` setting in `webpack.json` - my PR changes this. 

With my PR and `devtool: source-map` pausing on breakpoints works both in Chrome and Webstorm. 
Probably some less slow devtool settings work too. Just play around with it.
